### ISSUE TITLE
Few Bugs while Running the code

### ISSUE THREAD

**Issue by rameshfernandez** [christran/PHP-OOP-User-System-with-Bootstrap-Material-Design#5]
In the index page am getting this error

![image](https://cloud.githubusercontent.com/assets/7078137/8017999/40bdec3e-0c25-11e5-91f8-ecc58f1339ac.png)

Notice: Undefined property: stdClass::$title in D:\wamp\www\PHP-OOP-User-System-with-Bootstrap-Material-Design-master\index.php on line 83

( ! ) Notice: Undefined property: stdClass::$author in D:\wamp\www\PHP-OOP-User-System-with-Bootstrap-Material-Design-master\index.php on line 83

 Notice: Undefined property: stdClass::$body in D:\wamp\www\PHP-OOP-User-System-with-Bootstrap-Material-Design-master\index.php on line 85

Notice: Undefined property: stdClass::$date in D:\wamp\www\PHP-OOP-User-System-with-Bootstrap-Material-Design-master\index.php on line 88

Also the following getting error while adding News
Notice: Undefined variable: error in D:\wamp\www\PHP-OOP-User-System-with-Bootstrap-Material-Design-master\admin\news.php on line 47
![image](https://cloud.githubusercontent.com/assets/7078137/8017996/309d87ba-0c25-11e5-8fff-04f1820fc966.png)

there are some more errors/warnings in admin panel. 

where is the news table? should i create it? or do i missed it? Please help me to clear those errors. I'm new to OOP and PDO. i was using mysql functions.

**Comment by christran** [comment]
Sorry, looks like I forgot to include the news table in the SQL, if you create the table <b>news</b> with the columns <b>id</b>, <b>title</b>, <b>body</b>, <b>author</b>, and <b>date</b>

I think that should fix your errors.

**Comment by rameshfernandez** [comment]
Thanks for the immediate response Christran, 
i created a new table and its perfect with the above issue.. now i ave the following error
![image](https://cloud.githubusercontent.com/assets/7078137/8018621/4c6e9a1a-0c43-11e5-8089-c7db17f19360.png)

**Comment by christran** [comment]
Hmm that was the last page I worked on before I stopped updating this project. I just copied everything from news.php to members.php but I didn't finish changing all the sql queries in members.php

**Comment by rameshfernandez** [comment]
thank you again. do you have any idea about exporting to excel. for example exporting 10000 rows of userinfo to excel

**Comment by christran** [comment]
No idea, sorry.

**Comment by rameshfernandez** [comment]
anyway. Thanks

**Comment by arinyc** [comment]
This was OOPHP System was created by Alex Garrett on YouTube.
You stole this script.
